name: Build Java App

on:
  push:
    branches: [ main ]
    paths:
      - java-app/**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Code Quality Action
      id: checkstyle
      uses: ./.github/actions/java-code-quality
      with:
        working-directory: java-app
    - run: mkdir staging && cp target/*.jar staging
    # Upload the build artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
